version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - app-data:/app/data

volumes:
  app-data:
