name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: |
        chmod +x mvnw
        ./mvnw -B package --file pom.xml
    
    - name: Run tests
      run: ./mvnw test
    
    - name: Upload build artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: app-jar
        path: target/*.jar
        if-no-files-found: error
        retention-days: 5

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/download-artifact@v3
      with:
        name: app-jar
        path: target/
    
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: target/
